### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by TheClonerx** [nhammond129/ch.py#76]
This library predates the now standard async practices, implementing its own even loop.
This issue is more of a question if the change to async is planned or desired.

**Comment by asl97** [comment]
I am not planning any big changes, I am just here to fix my mess (joinThread) and I haven't touch on async much in python.

While it might better handle user who throw the async equivalent of time.sleep everywhere, ch.py simplistic way of handling stuff is quite nice

Beside, I do still want to remain compatible with past bots out there somehow, I am not even sure if async could add anything without breaking changes

**Comment by asl97** [comment]
Well, all the other issue reports been address as far as I am aware of, so I guess I try to address this from my own point of view

I uses async in javascript quite a lot, one thing about javascript is that it is basically already asynco everywhere, I uses async to bring some kind of synchronous structure to the code, it's great that way.

but in python, python is synchronous structured, the reason for using async is different from javascript, it is to allow for big code to be broken into tiny `tasklets` that can be run independently regardless of order and allowing blocking io task to give way to other tasks.

I am not sure what async could add to ch.py other than handling socket read and write to handle `select.select` limitation, assuming those still exists, since `feed` still has to be mostly process synchronous one at a time, the functions can't be change to async without breaking existing bots, all function isn't blocking anymore on the ch.py anyway and tasks would be a big mess to use async with the planned features.

Since it is still all single threaded, there isn't much benefit and just add complexity to the logic and traceback, as far as I am aware of.

While python async is basically like black magic to me I guess, if I had a bunch of task done with async, I guess it would look like the following code:

```python
class task():
  async tick(self):
    while true:
      await sleep(self.target-now)
      if self.condition:
        self.run()
        if not self.interval:
          break
```

I don't see how I could tell the amount of tasks that gotten overdue because of `feed` taking too long, time to next task to calculate if a task is taking too long to ensure it goes smoothly (`task.duration` > `(time to next task-avg(feed.duration))/overdue tasks`) without having most of the existing code, in which case we are just making it more complex just because of `async` with no real benefit.

The current main loop structure and tasks makes the above telemetric quite easy to implement, assuming I get around to doing it instead of being distracted by other stuff.

If you already have some example of improvement from using async, feel free to share, I will leave this open for now if anyone want to give example of actual implementation

____
Side note:

I know a few who modify `ch.py` to use threading, 4 threads per room for some in fact, I know personally of reports from those bot owner with issues of 100% cpu core usage and constant `'database'` corruption, It's probably their bad implementation that result in busy loop and thread race but I am not adding extra multi thread or multi process to ch.py, it shouldn't be needed since we have deferToThread

**Comment by asl97** [comment]
https://docs.python.org/3.10/library/asyncio-platforms.html

> Changed in version 3.8: On Windows, [ProactorEventLoop](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) is now the default event loop.
> 
> [ProactorEventLoop](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) has the following limitations:
> 
> The [loop.add_reader()](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.loop.add_reader) and [loop.add_writer()](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.loop.add_writer) methods are not supported.

😐, no simple add reader/writer

> await asyncio.get_running_loop().sock_connect(self.sock, (self._server, self._port))
> OSError: [WinError 10022] An invalid argument was supplied

😐, wtf why I can't use sock_connect

> self.sock = socket.socket()
> self.sock.connect_ex((self._server, self._port))
> self.__async_reader, self.__async_writer = await asyncio.open_connection(sock=self.sock)

or

> self.__async_reader, self.__async_writer = await asyncio.open_connection(self._server, self._port)

==

> KeyboardInterrupt
> Segmentation fault

?! 😐😕

I don't like that it `Segmentation fault` when `KeyboardInterrupt`-ed,  gonna put this on hold until I get a better idea that doesn't involve SelectorEventLoop since there be little to no advantage over the current select.select loop

**Comment by TheClonerx** [comment]
Have you tried loop.create_connection?
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection

Jul 6, 2023 16:37:41 asl97 ***@***.***>:

**Comment by asl97** [comment]
> Have you tried loop.create_connection? https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection

That seem like we need another class for a callback 'protocol' and it enough of a pain to know so much about asyncio

I just decide to use 'locking' via `asyncio.Event` and this dumb thing

https://github.com/nhammond129/ch.py/blob/3402b230327de85d038b657c4eb4993513f2ee39/ch/mixin/asyncio_cores.py#L72-L79

Usage is via mixin like all other mixin, the only exception is that you have to import `ch.mixin.asyncio_cores` directly.
because it has side effect, kind of like `__future__`, it modify one part about the ch module. that being the ch.Task class.

```python
# a simpler implementation using reader/writer without modifying the original handling much
class TestBot(ch.mixin.asyncio_cores.Asyncio_LWMCore, ch.RoomManager):
# or 
# should only be used on windows because it's stupid
class TestBot(ch.mixin.asyncio_cores.Asyncio_IOCPCore, ch.RoomManager):
```

**Comment by asl97** [comment]
Everything on the user (bot) end is the same,  if users really want to use asynco, they have to wrap their function in `create_task` or `ensure_future`.

I am not adding a wrapper to the library as I still feel async just complicate things. especially when misused.

**Comment by asl97** [comment]
I assume there no issue with this implementation and will be closing this.

side note: LWM just mean Linux Window Mac, it doesn't have any stdlib specific meaning,  IOCP is from the stdlib though https://docs.python.org/3.6/library/asyncio-eventloops.html#asyncio.ProactorEventLoop
